insert into peliculas(id_sucursal, Titulos, Anyo_lanzamiento, Duracion, Genero, Director, Protagonista)
VALUES('001','Shrek','2001','90 min','comedia/fantasia','Andrew Adamson, Vicky Jenson','Myke Myers')
insert into peliculas(id_sucursal, Titulos, Anyo_lanzamiento, Duracion, Genero, Director, Protagonista)
VALUES('001','Titanic','1997','194 min','drama','James Cameron','Leonardo Dicaprio')
insert into peliculas(id_sucursal, Titulos, Anyo_lanzamiento, Duracion, Genero, Director, Protagonista)
VALUES('001','Regreso al futuro','1985','116 min','ciencia ficción','Robert Zemeckis','Michael J. Fox')
insert into peliculas(id_sucursal, Titulos, Anyo_lanzamiento, Duracion, Genero, Director, Protagonista)
VALUES('001','Los Goonies','1985','114 min','comedia/aventura','Richard Donner','Sean Astin')
insert into peliculas(id_sucursal, Titulos, Anyo_lanzamiento, Duracion, Genero, Director, Protagonista)
VALUES('001','Gladiator','2000','155 min','acción/drama','Ridley Scott','Russell Crowe')
insert into peliculas(id_sucursal, Titulos, Anyo_lanzamiento, Duracion, Genero, Director, Protagonista)
VALUES('001','Batman','1989','126 min','acción/aventura','Tim Burton','Michael Keaton')
insert into peliculas(id_sucursal, Titulos, Anyo_lanzamiento, Duracion, Genero, Director, Protagonista)
VALUES('001','La comunidad del anillo','2001','228 min','fantasía/aventura','Peter Jackson','Elijah Wood')
insert into peliculas(id_sucursal, Titulos, Anyo_lanzamiento, Duracion, Genero, Director, Protagonista)
VALUES('001','Donnie Darko','2001','113 min','ciencia ficcón/fantasía','Richard Kelly','Jake Gyllenhaal')
insert into peliculas(id_sucursal, Titulos, Anyo_lanzamiento, Duracion, Genero, Director, Protagonista)
VALUES('001','Las dos torres','2002','235 min','fantasía/aventura','Oeter Jackson','Elijah Wood')
insert into peliculas(id_sucursal, Titulos, Anyo_lanzamiento, Duracion, Genero, Director, Protagonista)
VALUES('001','Spider-Man','2002','121 min','acción/ciencia ficcón','Sam Raimi','Tobey Maguire')
insert into peliculas(id_sucursal, Titulos, Anyo_lanzamiento, Duracion, Genero, Director, Protagonista)
VALUES('001','Spider-Man 2','2004','127 min','acción/ciencia ficcón','Sam Raimi','Tobey Maguire')
insert into peliculas(id_sucursal, Titulos, Anyo_lanzamiento, Duracion, Genero, Director, Protagonista)
VALUES('001','Spider-Man 3','2007','139 min','acción/ciencia ficcón','Sam Raimi','Tobey Maguire')
insert into peliculas(id_sucursal, Titulos, Anyo_lanzamiento, Duracion, Genero, Director, Protagonista)
VALUES('001','Encanto','2021','159 min','infantil/musical','Byron Howard, Jared Bush','Stephanie Beatriz')
insert into peliculas(id_sucursal, Titulos, Anyo_lanzamiento, Duracion, Genero, Director, Protagonista)
VALUES('001','COCO','2017','105 min','infantil/aventura','Adrián Molina, Lee Unkrich','Anthony Gonzalez')
insert into peliculas(id_sucursal, Titulos, Anyo_lanzamiento, Duracion, Genero, Director, Protagonista)
VALUES('001','El retorno del rey','2003','263 min','fantasía/aventura','Peter Jackson','Elijah Wood')
insert into peliculas(id_sucursal, Titulos, Anyo_lanzamiento, Duracion, Genero, Director, Protagonista)
VALUES('001','Ratatouille','2007','110 min','infantil/comedia','Brad Bird','Lou Romano')
insert into peliculas(id_sucursal, Titulos, Anyo_lanzamiento, Duracion, Genero, Director, Protagonista)
VALUES('001','La princesa Mononoke','1997','133 min','fantasía/aventura','Hayao Miyazaki','Yōji Matsuda')
insert into peliculas(id_sucursal, Titulos, Anyo_lanzamiento, Duracion, Genero, Director, Protagonista)
VALUES('001','El viaje de Chihiro','2001','125 min','fantasía/aventura','Hayao Miyazaki','Rumi Hiiragi')
insert into peliculas(id_sucursal, Titulos, Anyo_lanzamiento, Duracion, Genero, Director, Protagonista)
VALUES('001','Rogue One: una historia de Star Wars','2016','133 min','ciencia ficción/acción','Gareth Edwards','Felicity Jones')
insert into peliculas(id_sucursal, Titulos, Anyo_lanzamiento, Duracion, Genero, Director, Protagonista)
VALUES('001','Spider-Man: un nuevo universo','2018','120 min','infantil/acción','Peter Ramsey','Jake Johnson')
insert into peliculas(id_sucursal, Titulos, Anyo_lanzamiento, Duracion, Genero, Director, Protagonista)
VALUES('001','Hércules','1997','93 min','acción/fantasía','Ron Clements, John Musker','Tate Donovan')
insert into peliculas(id_sucursal, Titulos, Anyo_lanzamiento, Duracion, Genero, Director, Protagonista)
VALUES('001','Captain Fantastic','2016','120 min','drama/comedia','Matt Ross','Viggo Mortensen')
insert into peliculas(id_sucursal, Titulos, Anyo_lanzamiento, Duracion, Genero, Director, Protagonista)
VALUES('001','Shrek 2','2004','115 min','comedia/infantil','Andrew Adamson','Myke Myers')
insert into peliculas(id_sucursal, Titulos, Anyo_lanzamiento, Duracion, Genero, Director, Protagonista)
VALUES('001','Shrek Tercero','2007','93 min','comedia/infantil','Chris Miller','Myke Myers')
insert into peliculas(id_sucursal, Titulos, Anyo_lanzamiento, Duracion, Genero, Director, Protagonista)
VALUES('001','El rey león','1994','89 min','musical/infantil','Roger Allers','Mathew Broderick')
insert into peliculas(id_sucursal,Titulos,Anyo_lanzamiento,Duracion,Genero,Director,Protagonista)
values('001','Toy Story','1995','81 min','Animación','Jhon Lasseter','Tom Hanks')
insert into peliculas(id_sucursal,Titulos,Anyo_lanzamiento,Duracion,Genero,Director,Protagonista)
values('001','Toy Story 2','1999','93 min','Animación','Jhon Lasseter','Tom Hanks')
insert into peliculas(id_sucursal,Titulos,Anyo_lanzamiento,Duracion,Genero,Director,Protagonista)
values('001','Toy Story 3','2010','103 min','Animación','Jhon Lasseter','Tom Hanks')
insert into peliculas(id_sucursal,Titulos,Anyo_lanzamiento,Duracion,Genero,Director,Protagonista)
values('001','Toy story 4','2019','100 min','Animación','Jhon Lasseter','Tom Hanks')
insert into peliculas(id_sucursal,Titulos,Anyo_lanzamiento,Duracion,Genero,Director,Protagonista)
values('001','La naranja mecánica','1917','136 min','Drama/comedia negra','Stanley Kubrick','Malcolm McDowell')
insert into peliculas(id_sucursal,Titulos,Anyo_lanzamiento,Duracion,Genero,Director,Protagonista)
values('001','DJango Desencadenado','2012','170 min','Western Dramático','Quentin Tarantino','Jamie Foxx')
insert into peliculas(id_sucursal,Titulos,Anyo_lanzamiento,Duracion,Genero,Director,Protagonista)
values('001','Star Wars: La amenaza fantasma','1999','136 min','Ciencia ficción','George Lucas','Liam Neeson')
insert into peliculas(id_sucursal,Titulos,Anyo_lanzamiento,Duracion,Genero,Director,Protagonista)
values('001','Star Wars: El ataque de los clones','2002','142 min','Ciencia ficción','George Lucas','Ewan McGregor')
insert into peliculas(id_sucursal,Titulos,Anyo_lanzamiento,Duracion,Genero,Director,Protagonista)
values('001','Star Wars: La venganza de los Sith','2005','139 min','Ciencia ficción','George Lucas','Ewan McGregor')
insert into peliculas(id_sucursal,Titulos,Anyo_lanzamiento,Duracion,Genero,Director,Protagonista)
values('001','Star Wars: Una nueva esperanza','1977','125 min','Ciencia ficción','George Lucas','Mark Hamill')
insert into peliculas(id_sucursal,Titulos,Anyo_lanzamiento,Duracion,Genero,Director,Protagonista)
values('001','Star Wars: El imperio contraataca','1980','127 min','Ciencia ficción','Richard Marquand','Mark Hamill')
insert into peliculas(id_sucursal,Titulos,Anyo_lanzamiento,Duracion,Genero,Director,Protagonista)
values('001','Star Wars: El retorno del Jedi','1983','131 min','Ciencia ficción','Irvin Kershner','Mark Hamill')
insert into peliculas(id_sucursal,Titulos,Anyo_lanzamiento,Duracion,Genero,Director,Protagonista)
values('001','Star Wars: El despertar de la fuerza','2015','135 min','Ciencia ficción','J.J. Abrams','Harrison Ford')
insert into peliculas(id_sucursal,Titulos,Anyo_lanzamiento,Duracion,Genero,Director,Protagonista)
values('001','Star Wars: Los últimos jedi','2017','152 min','Ciencia ficción','Rian Jhonson','Mark Hamill')
insert into peliculas(id_sucursal,Titulos,Anyo_lanzamiento,Duracion,Genero,Director,Protagonista)
values('001','Star Wars: El ascenso de Skywalker','2019','142 min','Ciencia ficción','J.J. Abrams','Daisy Ridley')
insert into peliculas(id_sucursal,Titulos,Anyo_lanzamiento,Duracion,Genero,Director,Protagonista)
values('001','Pesadillas antes de Navidad','1993','73 min','Animación','Henry Selick','William Hickey')
insert into peliculas(id_sucursal,Titulos,Anyo_lanzamiento,Duracion,Genero,Director,Protagonista)
values('001','La novia cadáver','2005','76 min','Animación','Tim Burton','Jhonny Depp')
insert into peliculas(id_sucursal,Titulos,Anyo_lanzamiento,Duracion,Genero,Director,Protagonista)
values('001','Soy Leyenda','2007','101 min','Ciencia ficción','Francis Lawrence','Will Smith')
insert into peliculas(id_sucursal,Titulos,Anyo_lanzamiento,Duracion,Genero,Director,Protagonista)
values('001','El origen del planeta de los simios','2011','104 min','Ciencia ficción','Rupert Wyatt','James Franco')
insert into peliculas(id_sucursal,Titulos,Anyo_lanzamiento,Duracion,Genero,Director,Protagonista)
values('001','El amanecer del planeta de los simios','2014','131 min','Ciencia ficción','Matt Reeves','Jason clarke')
insert into peliculas(id_sucursal,Titulos,Anyo_lanzamiento,Duracion,Genero,Director,Protagonista)
values('001','La guerra del planeta de los simios','2017','140 min','Ciencia ficción','Matt Reeves','Andy Serkis')
insert into peliculas(id_sucursal,Titulos,Anyo_lanzamiento,Duracion,Genero,Director,Protagonista)
values('001','La cosa','1982','108 min','Ciencia ficción','Jhon Carpenter','Kurt Russell')
insert into peliculas(id_sucursal,Titulos,Anyo_lanzamiento,Duracion,Genero,Director,Protagonista)
values('001','Alien: El octavo pasajero','','','Ciencia ficción','Ridley Scott','Sigurney Weaver')
insert into peliculas(id_sucursal,Titulos,Anyo_lanzamiento,Duracion,Genero,Director,Protagonista)
values('001','Aliens: El regreso','1986','154 min','Ciencia ficción','James Cameron','Sigurney Weaver')
insert into peliculas(id_sucursal,Titulos,Anyo_lanzamiento,Duracion,Genero,Director,Protagonista)
values('001','Prometheus','2012','124 min','Ciencia ficción','Ridley Scott','Michael Fassbender')

