insert into videoclub(id,ciudad, idGerente)
VALUES ('001','Sevilla','006')
insert into videoclub(id,ciudad, idGerente)
VALUES ('002','Madrid','002')
insert into videoclub(id,ciudad, idGerente)
VALUES ('003','Barcelona','013')
insert into videoclub(id,ciudad, idGerente)
VALUES ('004','Valencia','019')
insert into videoclub(id,ciudad, idGerente)
VALUES ('005','Granada','10')



--Empleados

INSERT into empleados (nombre, apellidos, dni, email, ciudad, puesto, id_sucursal)
VALUES('Alberto','Baggins','65489345Y','albertomontero@gmail.com','Sevilla','recepcionista','001')
INSERT into empleados (nombre, apellidos, dni, email, ciudad, puesto, id_sucursal)
VALUES('Jorge','Bophîn','65458765T','jorgebophin@gmail.com','Madrid','Gerente','002')
INSERT into empleados (nombre, apellidos, dni, email, ciudad, puesto, id_sucursal)
VALUES('Andrés','Bolger','27659834R','andresbolger@gmail.com','Barcelona','Recepcionista','003')
INSERT into empleados (nombre, apellidos, dni, email, ciudad, puesto, id_sucursal)
VALUES('José','Sandyman','54782345Y','josesandyman@gmail.com','Valencia','Almacén','004')
INSERT into empleados (nombre, apellidos, dni, email, ciudad, puesto, id_sucursal)
VALUES('Álvaro','Noakes','67120965I','alvaronoakes@gmail.com','Granada','Marketing','005')
INSERT into empleados (nombre, apellidos, dni, email, ciudad, puesto, id_sucursal)
VALUES('Antonio','Brandagamba','78345623P','antoniobrandagamba@gmail.com','Sevilla','Gerente','001')
INSERT into empleados (nombre, apellidos, dni, email, ciudad, puesto, id_sucursal)
VALUES('Mónica','Brandybuck','45239865H','monicabrandybuck@gmail.com','Madrid','Recepcionista','002')
INSERT into empleados (nombre, apellidos, dni, email, ciudad, puesto, id_sucursal)
VALUES('Javier','Brockhouse','98214509L','javierbrockhouse@gmail.com','Barcelona','Marketing','003')
INSERT into empleados (nombre, apellidos, dni, email, ciudad, puesto, id_sucursal)
VALUES('Samuel','Labingi','87230978G','samuellabingi@gmail.com','Valencia','Administración','004')
INSERT into empleados (nombre, apellidos, dni, email, ciudad, puesto, id_sucursal)
VALUES('Andrés','Brownlock','32763456K','andresbrownlock@gmail.com','Granada','Gerente','005')
INSERT into empleados (nombre, apellidos, dni, email, ciudad, puesto, id_sucursal)
VALUES('José','Bancos','87234576J','josebancos@gmail.com','Sevilla','Administración','001')
INSERT into empleados (nombre, apellidos, dni, email, ciudad, puesto, id_sucursal)
VALUES('Adrián','Bunce','09124587R','adrianbunce@gmail.com','Madrid','Administración','002')
INSERT into empleados (nombre, apellidos, dni, email, ciudad, puesto, id_sucursal)
VALUES('David','Burrows','42398755J','davidburrows@gmail.com','Barcelona','Gerente','003')
INSERT into empleados (nombre, apellidos, dni, email, ciudad, puesto, id_sucursal)
VALUES('Manuel','Carnicero','87124576K','manuelcarnicero@gmail.com','Valencia','Recepcionista','004')
INSERT into empleados (nombre, apellidos, dni, email, ciudad, puesto, id_sucursal)
VALUES('Fernando','Cachero','98124576F','fernandocachero@gmail.com','Granada','Administración','005')
INSERT into empleados (nombre, apellidos, dni, email, ciudad, puesto, id_sucursal)
VALUES('Pablo','Clayhanger','09125698L','pabloclayhanger@gmail.com','Sevilla','Almacén','001')
INSERT into empleados (nombre, apellidos, dni, email, ciudad, puesto, id_sucursal)
VALUES('Laura','Diggie','12562398B','lauradiggie@gmail.com','Madrid','Administración','002')
INSERT into empleados (nombre, apellidos, dni, email, ciudad, puesto, id_sucursal)
VALUES('Paco','Fairbairn','98125634K','pacofairbairn@gmail.com','Barcelona','Marketing','003')
INSERT into empleados (nombre, apellidos, dni, email, ciudad, puesto, id_sucursal)
VALUES('María','Fallohide','98571598K','mariafallohide@gmail.com','Valencia','Gerente','004')
INSERT into empleados (nombre, apellidos, dni, email, ciudad, puesto, id_sucursal)
VALUES('Ana','Galbasi','98126534V','anagalbassi@gmail.com','Granada','Almacén','005')
INSERT into empleados (nombre, apellidos, dni, email, ciudad, puesto, id_sucursal)
VALUES('Carmen','Galpsi','09457845G','carmengalpsi@gmail.com','Sevilla','Marketing','001')
INSERT into empleados (nombre, apellidos, dni, email, ciudad, puesto, id_sucursal)
VALUES('Jaime','Gamgee','98345687D','jaimegamgee@gmail.com','Madrid','Almacén','002')
INSERT into empleados (nombre, apellidos, dni, email, ciudad, puesto, id_sucursal)
VALUES('Sara','Tuk','12904587U','saratuk@gmail.com','Barcelona','Marketing','003')
INSERT into empleados (nombre, apellidos, dni, email, ciudad, puesto, id_sucursal)
VALUES('Nadia','Brandigamo','23568745L','nadiabrandigamo@gmail.com','Valencia','Administración','004')
INSERT into empleados (nombre, apellidos, dni, email, ciudad, puesto, id_sucursal)
VALUES('Lucas','Ziñatiesa','12457634I','lucasziñatiesa@gmail.com','Granada','Recepcionista','005')




